files:
  excluded_extensions: [pdf, dat, db, py, yml, png, pdf, xlsx]
  excluded_names: [_ave, _max]
  excluded_paths: [Analysis]
movie:
    rot90: 0 # Needs to be set before loading the experiment
    # For TIR-T, V and ObjTIR, check the image orientation setting of the measurement software (Solis or MetaMorph).
# compute_image:  # no longer used. See show_movie>>frames_for_show_movie
#  number_of_frames: all
show_movie:
  image: average_image
  annotate: False
  frames_for_show_movie:
    first_frame: 0
    last_frame: 9
  illumination: None
find_coordinates:
  channels:
      - donor
  illumination: None # Set to None if single illumination configuration is used. Integer number to specify which illumination config will be used. The same order that the illuminations were used during the measurement.
  projection_image_type: average # Choose average or maximum
  method: by_channel # Choose by_channel, average_channels or sum_channels
  frames_for_peak_finding:
    first_frame: 0
    last_frame: 9
  sliding_window:
    use_sliding_window: False
    window_size: 20
    minimal_point_separation: 2
  peak_finding:
      method: local-maximum
      minimum_intensity_difference: 100
      maximum_intensity_difference: 1000000  # Optional
      filter_neighbourhood_size_min: 10  # Optional
      filter_neighbourhood_size_max: 10  # Optional
  coordinate_optimization:
      coordinates_within_margin:  # Optional
          margin: 20
      coordinates_after_gaussian_fit:  # Optional
          gaussian_width: 9
      coordinates_without_intensity_at_radius:  # Optional
          radius: 4
          cutoff: image_median
          fraction_of_peak_max: 0.25
background:
  method: ROI_minimum
  frames_for_background: # 'last frame' can be set as 'last' to indicate the last frame of the movie
    first_frame: 0
    last_frame: 9
mapping:
    method: icp # Choose icp and nn
    distance_threshold: 3 # Only relevant for nn or icp
    transformation_type: polynomial # Choose linear, nonlinear or polynomial
    initial_translation: 'width/2' # 'width/2' or e.g. [1024,0]
    peak_finding:
        donor:
            method: local-maximum
            minimum_intensity_difference: 100
            filter_neighbourhood_size_min: 10  # Optional
            filter_neighbourhood_size_max: 10  # Optional
        acceptor:
            method: local-maximum
            minimum_intensity_difference: 100
            filter_neighbourhood_size_min: 10  # Optional
            filter_neighbourhood_size_max: 10  # Optional
    coordinate_optimization:
        coordinates_after_gaussian_fit:  # Optional
            gaussian_width: 9
        coordinates_within_margin:  # Optional
            margin: 20
        coordinates_without_intensity_at_radius: # Optional
          radius: 4
          cutoff: image_median
          fraction_of_peak_max: 0.35
trace_extraction:
    channel: 'all'
    mask_size: TIR-T # float number, Presets: "TIR-T", "TIR-V", "TIR-S 1.5x 2x2", "TIR-S 1x 2x2"
    neighbourhood_size: 11
    subtract_background: True
    correct_illumination: False