find_coordinates:
    channel: d
    peak_finding:
        method: local-maximum
        threshold: 10
    coordinate_optimization:
        coordinates_within_margin:
            margin: 20
        coordinates_after_gaussian_fit:
            gaussian_width: 9
        coordinates_without_intensity_at_radius:
            radius: 4
            cutoff: image_median
            fraction_of_peak_max: 0.25
mapping:
    peak_finding:
        method: local-maximum
        threshold: 10
    coordinate_optimization:
        coordinates_after_gaussian_fit:
            gaussian_width: 9
        coordinates_without_intensity_at_radius:
            radius: 4
            cutoff: image_median
            fraction_of_peak_max: 0.35
        coordinates_within_margin:
            margin: 20
