name: trace_analysis
channels:
- conda-forge
dependencies:
- python=3.9
- pip=22.1
- numpy=1.22
- matplotlib-base=3.5
- matplotlib-venn=0.11
- pathlib2=2.3
- opencv=4.5
- tabulate=0.8
- scipy=1.8
- scikit-image=0.19
- scikit-learn=1.0
- pyyaml=6.0
- pandas=1.4
- seaborn=0.11
- openpyxl=3.0
- sphinx=4.4
- sphinx_rtd_theme=1.0
- gitpython=3.1
- nd2reader=3.3
- shapely=1.8
- xarray=2022.3
- netcdf4=1.5
- h5netcdf=1.0
- dask=2022.2
- dask-image=2021.12
- bottleneck=1.3
- tifffile=2022.5.4
- biopython=1.79
- bioconda::logomaker=0.8
- tqdm=4.63
- hmmlearn=0.2.7
- pyside2=5.13
