name: trace_analysis
channels:
- conda-forge
dependencies:
- python=3.9
- pip=21.1
- numpy=1.21
- wxpython=4.1
- matplotlib=3.4
- matplotlib-venn=0.11
- pathlib2=2.3
- opencv=4.5
- tabulate=0.8
- scipy=1.8
- scikit-image=0.18
- scikit-learn=0.24
- pyyaml=5.4
- pandas=1.2
- seaborn=0.11
- openpyxl=3.0
- sphinx=4.0
- sphinx_rtd_theme=0.5
- git=2.30
- gitpython=3.1
- nd2reader=3.3
- shapely=1.7
- xarray=0.18
- netcdf4=1.5
- h5netcdf=0.11
- dask=2021.6
- bottleneck=1.3
- tifffile=2021.6
- biopython=1.79
- bioconda::logomaker=0.8
- tqdm=4.62
